version: '3.8'

services:
  user1:
    build: ./pcuser1
    container_name: user1
    networks:
      default:
        ipv4_address: 192.168.200.4

  user2:
    build: ./pcuser1
    container_name: user2
    networks:
      default:
        ipv4_address: 192.168.200.5

  soa_ext:
    build: ./soa_ext
    container_name: soa_ext
    networks:
      default:
        ipv4_address: 192.168.200.6
    ports:
      - "192.168.100.4:53:53/tcp"
      - "192.168.100.4:53:53/udp"    

  soa_int:
    build: ./soa_int
    container_name: soa_int
    networks:
      default:
        ipv4_address: 192.168.200.7

  web:
    build: ./web
    container_name: web
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 192.168.200.8

  #b2b:
  #  build: ./b2b
  #  container_name: b2b
  #  ports:
  #    - "8080:80"
  #  networks:
  #    default:
  #      ipv4_address: 192.168.200.9
  
  intranet:
    build: ./intranet
    container_name: intranet
    networks:
      default:
        ipv4_address: 192.168.200.10

  mail:
    build: ./mail
    container_name: mail
    networks:
      default:
        ipv4_address: 192.168.200.11

  db:
    build: ./db
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: woodyToys
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 192.168.200.12

  resolver:
    build: ./resolver
    container_name: resolver
    depends_on:
      - soa_int
    networks:
      default:
        ipv4_address: 192.168.200.13

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

volumes:
  db_data:
