version: '3.8'

services:

  user1:
    build: ./pcuser1
    container_name: user1
    networks:
      woodytoys:
        ipv4_address: 192.168.200.4

  soa:
    build: ./soa
    container_name: soa
    networks:
      woodytoys:
        ipv4_address:  192.168.200.5

  resolver:
    build: ./resolver
    container_name: resolver
    depends_on:
      - soa
    networks:
      woodytoys:
        ipv4_address: 192.168.200.6

  db:
    build: ./db
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: woodyToys
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      woodytoys:
        ipv4_address:  192.168.200.7

  web:
    build: ./web
    container_name: web
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      woodytoys:
        ipv4_address:  192.168.200.8
  
  mail:
    build: ./mail
    container_name: mail
    networks:
      woodytoys:
        ipv4_address: 192.168.200.9

networks:
  woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

volumes:
  db_data:
