version: '3.8'

services:

  user1:
    build: ./pcuser1
    container_name: user1
    networks:
      lan:
        ipv4_address: 192.168.200.4

  user2:
    build: ./pcuser1
    container_name: user2
    networks:
      lan:
        ipv4_address: 192.168.200.5

  soa_ext:
    build: ./soa_ext
    container_name: soa_ext
    networks:
      dmz:
        ipv4_address: 192.168.300.4

  soa_int:
    build: ./soa_int
    container_name: soa_int
    networks:
      trusted_zone:
        ipv4_address: 192.168.400.4

  web1:
    build: ./web1
    container_name: web1
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      dmz:
        ipv4_address: 192.168.300.5

  b2b:
    build: ./b2b
    container_name: b2b
    networks:
      dmz:
        ipv4_address: 192.168.300.6

  mail:
    build: ./mail
    container_name: mail
    networks:
      dmz:
        ipv4_address: 192.168.300.7

  db:
    build: ./db
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: woodyToys
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      dmz2:
        ipv4_address: 192.168.301.4

  resolver:
    build: ./resolver
    container_name: resolver
    depends_on:
      - soa_int
    networks:
      trusted_zone:
        ipv4_address: 192.168.400.5

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

  dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.300.0/24

  dmz2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.301.0/24

  trusted_zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.400.0/24

volumes:
  db_data:
