FROM ubuntu:latest

RUN apt-get update

RUN apt install dnsutils -y
RUN apt install iputils-ping -y
RUN apt install links -y
RUN apt install nano

ADD --chown=root:root resolv.conf /etc/resolv.conf


CMD tail -f /dev/null


